### PR TITLE
Updated scrape.py

### PR DESCRIPTION
**Pull request by anirudh-hegde**
Added some dependencies of chromedriver and chrome and also versions of chrome and chromedriver should be compatible.
Add the path of chromedriver and chrome(google-chrome) of your system to scrape.py.
However I have added the path for chromedriver and chrome(google-chrome) of my system to scrape.py.

Prerequisites:
Install ChromeDriver and google-chrome of compatible version 

My System details:

Description: Ubuntu 23.10
Release:	23.10
Codename: mantic

chromedriver version: ChromeDriver 120.0.6099.109 (3419140ab665596f21b385ce136419fde0924272-refs/branch-heads/6099@{#1483})

google-chrome version: Google Chrome 120.0.6099.129

### CODE REVIEW

**Comment by TeeWrath** [comment]
@anirudh-hegde can you try to make it such that it is not system specific and can work on any system ?

**Comment by anirudh-hegde** [comment]
> @anirudh-hegde can you try to make it such that it is not system specific and can work on any system ?

Ya I will try

**Comment by anirudh-hegde** [comment]
Hey @TeeWrath,

chrome_path = "/path/to/google-chrome"  # Insert the file path of Google Chrome on your system
chromedriver_path = "/path/to/chromedriver"  # Insert the file path of ChromeDriver on your system

Replace "/path/to/google-chrome" with the actual file path to the Google Chrome executable on your system, and "/path/to/chromedriver" with the actual file path to the ChromeDriver executable on your system. Ensure that you have downloaded the compatible version of ChromeDriver for your Google Chrome installation.

**Comment by anirudh-hegde** [comment]
Hey
I am opening another pull request  with another branch so I close this pull-request

**Pull request closed without merging**
